name: VMCEssentials
version: 1.0.0
api-version: 1.15
author: Twijn
main: net.valoranmc.essentials.VMCEssentials

commands:
  fly:
    permission: vmce.fly
    usage: /<command>
  nick:
    permission: vmce.nick
    usage: /<command> [Player] <Nickname>
  tpo:
    permission: vmce.tpo
    usage: /<command> <Player>
  tpohere:
    permission: vmce.tpohere
    usage: /<command> <Player>
  tpa:
    default: vmce.tpa
    usage: /<command> <Player>
  tpahere:
    default: vmce.tpahere
    usage: /<command> <Player>
  tpaccept:
    default: vmce.tpaccept
    usage: /<command> <Player>
  tpdeny:
    default: vmce.tpdeny
    usage: /<command>
  gamemode:
    permission: vmce.gamemode.command
    usage: /<command> [Player] <Gamemode>
  gma:
    permission: vmce.gamemode.adventure
    usage: /<command>
  gmc:
    permission: vmce.gamemode.creative
    usage: /<command>
  gms:
    permission: vmce.gamemode.survival
    usage: /<command>
  gmsp:
    permission: vmce.gamemode.spectator
    usage: /<command>

permissions:
  vmce.fly:
    default: op
    description: Permission to use /fly
  vmce.fly.others:
    default: op
    description: Permission to use /fly on others
  vmce.nick:
    default: op
    description: Permission to use /nick
  vmce.nick.others:
    default: op
    description: Permission to use /nick on others
  vmce.tpo:
    default: op
    description: Permission to use /tpo
  vmce.tpohere:
    default: op
    description: Permission to use /tpohere
  vmce.tpa:
    default: true
    description: Permission to use /tpa
  vmce.tpahere:
    default: true
    description: Permission to use /tpahere
  vmce.tpaccept:
    default: true
    description: Permission to use /tpaccept
  vmce.tpdeny:
    default: true
    description: Permission to use /tpdeny
  vmce.gamemode.*:
    description: Gives permission to all Gamemode related commands
    children:
      vmce.gamemode.command: true
      vmce.gamemode.adventure: true
      vmce.gamemode.creative: true
      vmce.gamemode.survival: true
      vmce.gamemode.spectator: true
  vmce.gamemode.command:
    description: Permission to use /gamemode
    default: op
  vmce.gamemode.command.others:
    description: Permission to use /gamemode on others
    default: op
  vmce.gamemode.adventure:
    description: Gives permission to enter adventure mode
    default: op
    children:
      vmce.gamemode.command: true
  vmce.gamemode.creative:
    description: Gives permission to enter creative mode
    default: op
    children:
      vmce.gamemode.command: true
  vmce.gamemode.survival:
    description: Gives permission to enter survival mode
    default: op
    children:
      vmce.gamemode.command: true
  vmce.gamemode.spectator:
    description: Gives permission to enter spectator mode
    default: op
    children:
      vmce.gamemode.command: true